export type Bio2Question = {
  id: string;
  type?: 'multiple_choice' | 'open';
  category: string;
  sub_topic: string;
  prompt: string;
  options?: string[];
  correct_answer: string;
  explanation: string;
};

export const SUB_TOPIC_LABELS: Record<string, string> = {
  fit_blijven: '4.1 Fit blijven',
  spieren_pezen: '4.2 Spieren & pezen',
  skelet: '4.3 Skelet',
  botverbindingen: '4.4 Botverbindingen',
  blessures: '4.5 Blessures',
  steunweefsels: '4.6 Steunweefsels',
  skeletten_vergelijken: '4.7 Skeletten vergelijken',
};

export const BIO2_QUESTIONS: Bio2Question[] = [
  // ── 4.1 Fit blijven ──────────────────────────────────────────────────────
  {
    id: 'b2_01',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Welke drie onderdelen zorgen samen voor beweging?',
    options: ['Botten, spieren en gewrichten', 'Hersenen, zenuwen en spieren', 'Huid, spieren en botten', 'Gewrichten, pezen en zenuwen'],
    correct_answer: 'Botten, spieren en gewrichten',
    explanation: 'Botten geven stevigheid, spieren zorgen voor beweging, gewrichten zijn de scharnieren.',
  },
  {
    id: 'b2_02',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Wat is GEEN functie van bewegen?',
    options: ['Spierkracht wordt groter', 'Uithoudingsvermogen verbetert', 'Je botten worden langer', 'Je voelt je mentaal beter'],
    correct_answer: 'Je botten worden langer',
    explanation: 'Bewegen maakt spieren sterker en verbetert uithoudingsvermogen. Botlengte wordt bepaald door groei, niet door bewegen.',
  },
  {
    id: 'b2_03',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Waarom is bewegen goed voor je geestelijke gezondheid?',
    options: ['Je botten worden harder', 'Er komen stoffen vrij die zorgen voor goed humeur', 'Je krijgt meer spiervezels', 'Je longen worden groter'],
    correct_answer: 'Er komen stoffen vrij die zorgen voor goed humeur',
    explanation: 'Door beweging komen er stoffen vrij in je lichaam die zorgen voor een goed humeur en minder stress.',
  },
  {
    id: 'b2_04',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Spieren kunnen samentrekken zodat ze botten in beweging brengen. Botten zijn stevig en hard. Kraakbeen is elastisch. Wat klopt er over kraakbeen?',
    options: ['Kraakbeen bevat veel bloedvaten', 'Kraakbeen is glad, zodat botten soepel langs elkaar bewegen', 'Kraakbeen is harder dan bot', 'Kraakbeen kan samentrekken'],
    correct_answer: 'Kraakbeen is glad, zodat botten soepel langs elkaar bewegen',
    explanation: 'Kraakbeen zit onder andere aan de uiteinden van botten. Het is glad, waardoor botten soepel langs elkaar bewegen. Kraakbeen bevat GEEN bloedvaten.',
  },
  {
    id: 'b2_05',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Wat gebeurt er als je te weinig beweegt?',
    options: ['Je spieren worden sterker', 'Je lichamelijke gezondheid gaat achteruit', 'Je botten worden flexibeler', 'Je uithoudingsvermogen neemt toe'],
    correct_answer: 'Je lichamelijke gezondheid gaat achteruit',
    explanation: 'Te weinig bewegen zorgt dat spieren minder sterk worden en je steeds moeilijker kunt bewegen.',
  },
  {
    id: 'b2_06',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Wat is spierkracht?',
    options: ['Hoe lang je een inspanning volhoudt', 'Hoe sterk je spieren zijn', 'Hoe snel je spieren samentrekken', 'Hoeveel spieren je hebt'],
    correct_answer: 'Hoe sterk je spieren zijn',
    explanation: 'Spierkracht = hoe sterk je spieren zijn. Uithoudingsvermogen = hoe lang je een inspanning volhoudt.',
  },
  {
    id: 'b2_07',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Wat is uithoudingsvermogen?',
    options: ['Hoe sterk je spieren zijn', 'Hoe snel je kunt rennen', 'Hoe lang je een inspanning kunt volhouden', 'Hoeveel je kunt tillen'],
    correct_answer: 'Hoe lang je een inspanning kunt volhouden',
    explanation: 'Uithoudingsvermogen = je longen nemen beter zuurstof op, je houdt een inspanning langer vol.',
  },

  // ── 4.2 Spieren & pezen ───────────────────────────────────────────────────
  {
    id: 'b2_08',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Waar is een skeletspier uit opgebouwd?',
    options: ['Beencellen', 'Spiervezels', 'Kraakbeencellen', 'Zenuwcellen'],
    correct_answer: 'Spiervezels',
    explanation: 'Een skeletspier is opgebouwd uit spiervezels. Spiervezels zijn lang en dun. Meerdere spiervezels vormen een spierbundel, meerdere spierbundels vormen een spier.',
  },
  {
    id: 'b2_09',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wat is de juiste volgorde van klein naar groot bij een spier?',
    options: ['Spierbundel → spiervezel → spier', 'Spier → spierbundel → spiervezel', 'Celkern → spiervezel → spierbundel → spier', 'Spiervezel → spier → spierbundel'],
    correct_answer: 'Celkern → spiervezel → spierbundel → spier',
    explanation: 'Van klein naar groot: celkernen zitten in spiervezels, meerdere spiervezels vormen een spierbundel, meerdere spierbundels vormen een spier.',
  },
  {
    id: 'b2_10',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wat gebeurt er als de biceps samentrekt?',
    options: ['Je onderarm gaat omlaag', 'Je onderarm beweegt omhoog', 'Je bovenarm wordt langer', 'Je hand opent zich'],
    correct_answer: 'Je onderarm beweegt omhoog',
    explanation: 'Als de biceps (spier aan de bovenkant van je bovenarm) samentrekt, buigt je arm en gaat je onderarm omhoog.',
  },
  {
    id: 'b2_11',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'De biceps en triceps zijn antagonisten. Wat betekent dat?',
    options: ['Ze werken samen', 'Ze zorgen voor tegengestelde bewegingen', 'Ze zitten aan dezelfde kant', 'Ze zijn even sterk'],
    correct_answer: 'Ze zorgen voor tegengestelde bewegingen',
    explanation: 'Antagonisten zijn twee spieren die tegengestelde bewegingen veroorzaken. Biceps buigt de arm, triceps strekt de arm.',
  },
  {
    id: 'b2_12',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wat is de functie van pezen?',
    options: ['Botten met elkaar verbinden', 'Spieren met botten verbinden', 'Gewrichten smeren', 'Kraakbeen beschermen'],
    correct_answer: 'Spieren met botten verbinden',
    explanation: 'Pezen verbinden je spieren met je skelet. Ze zijn taai en sterk en kunnen niet samentrekken.',
  },
  {
    id: 'b2_13',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Welke pees zit in je kuit?',
    options: ['Bicepspees', 'Kniepees', 'Achillespees', 'Rugpees'],
    correct_answer: 'Achillespees',
    explanation: 'De achillespees verbindt de kuitspier met het bot van je hiel. Deze pees trekt met veel kracht als je loopt en springt.',
  },
  {
    id: 'b2_14',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wat is het verschil tussen skeletspieren en gladde spieren?',
    options: ['Skeletspieren zitten aan botten, gladde spieren niet altijd', 'Gladde spieren zijn sterker', 'Skeletspieren zijn onvermoeibaar', 'Er is geen verschil'],
    correct_answer: 'Skeletspieren zitten aan botten, gladde spieren niet altijd',
    explanation: 'Skeletspieren zitten vast aan botten en kun je bewust aanspannen. Gladde spieren (darmen, bloedvaten) kun je niet bewust aanspannen en zijn onvermoeibaar.',
  },
  {
    id: 'b2_15',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Welke spier kun je NIET bewust aanspannen?',
    options: ['Biceps', 'Triceps', 'Hartspier', 'Kuitspier'],
    correct_answer: 'Hartspier',
    explanation: 'De hartspier en gladde spieren kun je niet bewust samentrekken of ontspannen. Skeletspieren (biceps, triceps, kuitspier) wel.',
  },
  {
    id: 'b2_16',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Langzame spiervezels zijn geschikt voor langdurige inspanning. Ze hebben een rode kleur. Snelle spiervezels zijn geschikt voor korte, hevige inspanning. Waarom is eendenvlees roder dan kippenvlees?',
    options: ['Eenden zijn groter', 'Eenden vliegen veel meer en hebben meer langzame spiervezels nodig', 'Kippen hebben geen spieren', 'Eenden eten ander voedsel'],
    correct_answer: 'Eenden vliegen veel meer en hebben meer langzame spiervezels nodig',
    explanation: 'Eenden vliegen veel meer dan kippen. Ze hebben meer langzame (rode) spiervezels nodig voor langdurige inspanning.',
  },
  {
    id: 'b2_17',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wanneer kan een skeletspier zich aanspannen ZONDER dat je beweegt?',
    options: ['Dat kan niet', 'Als je een dienblad vasthoudt of rechtop zit', 'Alleen tijdens het slapen', 'Alleen als je koud hebt'],
    correct_answer: 'Als je een dienblad vasthoudt of rechtop zit',
    explanation: 'Skeletspieren kunnen zich aanspannen zonder dat je beweegt, bijvoorbeeld als je rechtop zit of iets vasthoudt. De spieren houden je positie vast.',
  },
  {
    id: 'b2_18',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wat loopt er tussen de spierbundels van een skeletspier?',
    options: ['Kraakbeen', 'Bloedvaten en zenuwen', 'Bot', 'Pezen'],
    correct_answer: 'Bloedvaten en zenuwen',
    explanation: 'Tussen de spierbundels lopen bloedvaten (voor zuurstof en voedingsstoffen) en zenuwen (voor signalen van de hersenen).',
  },
  {
    id: 'b2_19',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Gladde spiertjes in je huid kunnen haartjes overeind laten staan. Hoe heet dat?',
    options: ['Spierkramp', 'Kippenvel', 'Verstuiking', 'Spierverrekking'],
    correct_answer: 'Kippenvel',
    explanation: 'Aan elk lichaamshaartje zit een glad spiertje. Als al die spiertjes tegelijk samentrekken, gaan de haartjes overeind staan: kippenvel.',
  },

  // ── 4.3 Skelet ───────────────────────────────────────────────────────────
  {
    id: 'b2_20',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Uit hoeveel botten bestaat het skelet van een volwassen mens?',
    options: ['106', '206', '306', '406'],
    correct_answer: '206',
    explanation: 'Het skelet van een volwassen mens bestaat uit 206 botten. Een baby heeft er meer (~350), want sommige botten groeien aan elkaar vast.',
  },
  {
    id: 'b2_21',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Wat is GEEN functie van het skelet?',
    options: ['Beweging mogelijk maken', 'Kwetsbare organen beschermen', 'Voedsel verteren', 'Rode bloedcellen aanmaken'],
    correct_answer: 'Voedsel verteren',
    explanation: 'Het skelet heeft 4 functies: beweging, bescherming van organen, stevigheid/vorm, en aanmaak van rode bloedcellen.',
  },
  {
    id: 'b2_22',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'De schedel beschermt de hersenen. Wat beschermt de borstkas?',
    options: ['De darmen', 'Het hart en de longen', 'De nieren', 'De spieren'],
    correct_answer: 'Het hart en de longen',
    explanation: 'De borstkas (ribben + borstbeen + borstwervels) beschermt het hart en de longen.',
  },
  {
    id: 'b2_23',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'De wervelkolom heeft een dubbele S-vorm. Waarom?',
    options: ['Dat ziet er mooi uit', 'Het werkt als een schokdemper', 'Zodat je langer bent', 'Om meer spieren vast te zetten'],
    correct_answer: 'Het werkt als een schokdemper',
    explanation: 'De dubbele S-vorm maakt de wervelkolom veerkrachtig en werkt als een schokdemper, bijvoorbeeld bij springen.',
  },
  {
    id: 'b2_24',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Wat zit er tussen de wervels?',
    options: ['Bot', 'Spieren', 'Tussenwervelschijven', 'Pezen'],
    correct_answer: 'Tussenwervelschijven',
    explanation: 'Tussen de wervels liggen tussenwervelschijven. Deze helpen bij soepel bewegen en het opvangen van schokken.',
  },
  {
    id: 'b2_25',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Uit welke drie soorten wervels bestaat de wervelkolom?',
    options: ['Grote, middel en kleine wervels', 'Halswervels, borstwervels en lendenwervels', 'Schedel, rug en staart wervels', 'Boven, midden en onder wervels'],
    correct_answer: 'Halswervels, borstwervels en lendenwervels',
    explanation: 'De wervelkolom bestaat uit halswervels, borstwervels en lendenwervels. Hoe lager, hoe groter (meer gewicht dragen). Daaronder zitten het heiligbeen en staartbeen.',
  },
  {
    id: 'b2_26',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Wat is het neusbeen?',
    options: ['Een groot bot in je neus', 'Een klein bot bovenaan je neus', 'Het kraakbeen van je neus', 'Het bot achter je ogen'],
    correct_answer: 'Een klein bot bovenaan je neus',
    explanation: 'Het neusbeen is klein. Het grootste deel van je neus bestaat uit kraakbeen, niet uit bot.',
  },
  {
    id: 'b2_27',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Wat is bijzonder aan de onderkaak?',
    options: ['Het is het hardste bot', 'Het is het enige niet-vergroeide bot van je schedel', 'Het is het kleinste bot', 'Het bestaat uit kraakbeen'],
    correct_answer: 'Het is het enige niet-vergroeide bot van je schedel',
    explanation: 'De onderkaak zit los van de bovenkaak. Daardoor kun je bijten en kauwen. Alle andere schedelbotten zitten stevig aan elkaar vast.',
  },
  {
    id: 'b2_28',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Waaruit bestaat de schoudergordel?',
    options: ['Twee schouderbladen en twee sleutelbeenderen', 'Twee ribben en het borstbeen', 'Het opperarmbeen en de ellepijp', 'Twee heupbeenderen'],
    correct_answer: 'Twee schouderbladen en twee sleutelbeenderen',
    explanation: 'De schoudergordel zorgt dat je armen aan je romp vastzitten. Hij bestaat uit twee schouderbladen en twee sleutelbeenderen.',
  },
  {
    id: 'b2_29',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Waaruit bestaat de bekkengordel?',
    options: ['Twee schouderbladen', 'Twee heupbeenderen, heiligbeen en staartbeen', 'Dijbeen en knieschijf', 'Borstwervels en ribben'],
    correct_answer: 'Twee heupbeenderen, heiligbeen en staartbeen',
    explanation: 'De bekkengordel ondersteunt je lichaam bij zitten, staan, lopen en springen.',
  },
  {
    id: 'b2_30',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Ezelsbruggetje: hoe onthoud je welk bot het spaakbeen is en welk de ellepijp?',
    options: ['Spaakbeen is langer', 'Pink begint met P = ellepijp aan de pink-kant', 'Spaakbeen zit aan de binnenkant', 'Ellepijp is dunner'],
    correct_answer: 'Pink begint met P = ellepijp aan de pink-kant',
    explanation: 'Ezelsbruggetje: Pink begint met een P, ellepijp eindigt met een P. De ellepijp zit aan de kant van je pink, het spaakbeen aan de kant van je duim.',
  },
  {
    id: 'b2_31',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'De onderarm en het onderbeen lijken op elkaar. Waaruit bestaan ze allebei?',
    options: ['Eén bot', 'Twee botten die naast elkaar liggen', 'Drie botten', 'Kraakbeen'],
    correct_answer: 'Twee botten die naast elkaar liggen',
    explanation: 'De onderarm heeft spaakbeen + ellepijp. Het onderbeen heeft scheenbeen + kuitbeen. Twee botten naast elkaar.',
  },
  {
    id: 'b2_32',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Hoeveel vingerkootjes heeft elke vinger?',
    options: ['2', '3', '4', '5'],
    correct_answer: '3',
    explanation: 'Elke vinger heeft drie kootjes, behalve de duim en de grote teen — die hebben er twee.',
  },

  // ── 4.4 Botverbindingen ───────────────────────────────────────────────────
  {
    id: 'b2_33',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Wat is een gewricht?',
    options: ['Een bot', 'Een verbinding tussen botten die beweging mogelijk maakt', 'Een spier', 'Een pees'],
    correct_answer: 'Een verbinding tussen botten die beweging mogelijk maakt',
    explanation: 'Gewrichten zijn een soort scharnieren. Ze maken het mogelijk dat botten ten opzichte van elkaar kunnen bewegen.',
  },
  {
    id: 'b2_34',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Welk gewricht kan in ALLE richtingen bewegen?',
    options: ['Scharniergewricht', 'Kogelgewricht', 'Rolgewricht', 'Naadverbinding'],
    correct_answer: 'Kogelgewricht',
    explanation: 'Het kogelgewricht kan in alle richtingen bewegen. Voorbeelden: schoudergewricht en heupgewricht.',
  },
  {
    id: 'b2_35',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'De knie en de elleboog zijn voorbeelden van een...',
    options: ['Kogelgewricht', 'Rolgewricht', 'Scharniergewricht', 'Kraakbeenverbinding'],
    correct_answer: 'Scharniergewricht',
    explanation: 'Een scharniergewricht kan in twee richtingen bewegen: strekken en buigen. De knie en de elleboog zijn scharniergewrichten.',
  },
  {
    id: 'b2_36',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Wat maakt een rolgewricht mogelijk?',
    options: ['Buigen en strekken', 'Bewegen in alle richtingen', 'Een rolbeweging van een bot', 'Geen beweging'],
    correct_answer: 'Een rolbeweging van een bot',
    explanation: 'Het rolgewricht bij je elleboog zorgt dat je spaakbeen over je ellepijp kan rollen als je je hand omdraait.',
  },
  {
    id: 'b2_37',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Wat is de gewrichtskom?',
    options: ['De ronding van een bot', 'De holte waarin de gewrichtskop past', 'Het kapsel om het gewricht', 'De smeer in het gewricht'],
    correct_answer: 'De holte waarin de gewrichtskop past',
    explanation: 'Het ene botstuk heeft een holte (de gewrichtskom), het andere heeft een ronding (de gewrichtskop) die erin past.',
  },
  {
    id: 'b2_38',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Waarvoor dient gewrichtssmeer?',
    options: ['Om botten te laten groeien', 'Om het kraakbeen glad te houden en slijtage te voorkomen', 'Om spieren te voeden', 'Om botten hard te maken'],
    correct_answer: 'Om het kraakbeen glad te houden en slijtage te voorkomen',
    explanation: 'Gewrichtssmeer zorgt dat het kraakbeen glad blijft, het gewricht soepel werkt en slijtage wordt voorkomen.',
  },
  {
    id: 'b2_39',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Wat houdt de botstukken van een gewricht bij elkaar?',
    options: ['Spieren alleen', 'Het gewrichtskapsel en gewrichtsbanden', 'Kraakbeen', 'Beenmerg'],
    correct_answer: 'Het gewrichtskapsel en gewrichtsbanden',
    explanation: 'Het gewrichtskapsel omhult het gewricht. Gewrichtsbanden (bij knie, heup) geven extra stevigheid.',
  },
  {
    id: 'b2_40',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Tussenwervelschijven zijn een voorbeeld van een...',
    options: ['Gewricht', 'Naadverbinding', 'Kraakbeenverbinding', 'Kogelgewricht'],
    correct_answer: 'Kraakbeenverbinding',
    explanation: 'Tussenwervelschijven bestaan uit stevig kraakbeen. Ze verbinden de wervels en maken de wervelkolom buigzaam.',
  },
  {
    id: 'b2_41',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Schedelbeenderen zijn verbonden door een naadverbinding. Wat betekent dat?',
    options: ['Ze kunnen vrij bewegen', 'Ze zitten stevig vast en kunnen niet bewegen', 'Ze zijn verbonden door kraakbeen', 'Ze zitten los van elkaar'],
    correct_answer: 'Ze zitten stevig vast en kunnen niet bewegen',
    explanation: 'Door de gekartelde randen zitten de schedelbotten stevig aan elkaar. Ze vormen een geheel en beschermen de hersenen.',
  },
  {
    id: 'b2_42',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Wat zijn fontanellen?',
    options: ['Kleine botjes in je hand', 'Zachte plekken in de schedel van een baby', 'Gewrichtsbanden bij je knie', 'Botten in je voet'],
    correct_answer: 'Zachte plekken in de schedel van een baby',
    explanation: 'Bij een baby zitten de schedelbotten nog niet vast aan elkaar. Stevig weefsel onder de huid beschermt de hersenen. Na 12-18 maanden groeien de botten dicht.',
  },

  // ── 4.5 Blessures ─────────────────────────────────────────────────────────
  {
    id: 'b2_43',
    category: '4.5',
    sub_topic: 'blessures',
    prompt: 'Wat is een kneuzing?',
    options: ['Een gebroken bot', 'Een blauwe plek doordat weefsel onder de huid beschadigd is', 'Een gescheurde spier', 'Een ontwricht gewricht'],
    correct_answer: 'Een blauwe plek doordat weefsel onder de huid beschadigd is',
    explanation: 'Bij een kneuzing komt bloed en lichaamsvocht vrij onder de huid. Koel minimaal 20 minuten met ijs of een coolpack.',
  },
  {
    id: 'b2_44',
    category: '4.5',
    sub_topic: 'blessures',
    prompt: 'Wat is het verschil tussen een verstuiking en een ontwrichting?',
    options: ['Er is geen verschil', 'Bij verstuiking gaan botten terug, bij ontwrichting blijven ze verkeerd staan', 'Verstuiking is erger', 'Ontwrichting geneest vanzelf'],
    correct_answer: 'Bij verstuiking gaan botten terug, bij ontwrichting blijven ze verkeerd staan',
    explanation: 'Bij een verstuiking rekken spieren/pezen/banden uit maar komen de botten terug. Bij een ontwrichting blijven de botten verkeerd staan — een arts moet ze terugzetten.',
  },
  {
    id: 'b2_45',
    category: '4.5',
    sub_topic: 'blessures',
    prompt: 'Hoe herken je een botbreuk?',
    options: ['Je hebt alleen een blauwe plek', 'Pijn, zwelling, bloeduitstorting, soms steekt het bot door de huid', 'Je kunt normaal bewegen', 'Het bot wordt zachter'],
    correct_answer: 'Pijn, zwelling, bloeduitstorting, soms steekt het bot door de huid',
    explanation: 'Bij een botbreuk heb je veel pijn op een bepaalde plaats, een zwelling en een bloeduitstorting. Je kunt vaak niet goed bewegen.',
  },
  {
    id: 'b2_46',
    category: '4.5',
    sub_topic: 'blessures',
    prompt: 'Wat laat een röntgenfoto goed zien?',
    options: ['Spieren en pezen', 'Botten', 'Hersenen', 'Bloedvaten'],
    correct_answer: 'Botten',
    explanation: 'Botten houden röntgenstraling tegen en zijn daarom goed te zien. Zachte weefsels (spieren) zijn nauwelijks zichtbaar op een röntgenfoto.',
  },
  {
    id: 'b2_47',
    category: '4.5',
    sub_topic: 'blessures',
    prompt: 'Wanneer gebruik je een MRI-scan in plaats van een röntgenfoto?',
    options: ['Altijd', 'Als je zachte weefsels wilt bekijken, zoals hersenen en spieren', 'Alleen bij kinderen', 'Nooit, röntgen is altijd beter'],
    correct_answer: 'Als je zachte weefsels wilt bekijken, zoals hersenen en spieren',
    explanation: 'MRI werkt met magnetische straling en radiogolven. Het laat zachte weefsels goed zien, maar je moet heel stil liggen.',
  },
  {
    id: 'b2_48',
    category: '4.5',
    sub_topic: 'blessures',
    prompt: 'Wat moet je doen bij een verstuikte enkel?',
    options: ['Doorlopen', 'Snel koelen en een drukverband aanleggen, rust geven', 'Meteen naar het ziekenhuis', 'Warm maken'],
    correct_answer: 'Snel koelen en een drukverband aanleggen, rust geven',
    explanation: 'Bij een verstuiking: koelen, drukverband, rust. Als je na een uur nog niet goed kunt staan, neem contact op met de huisarts.',
  },

  // ── 4.6 Steunweefsels ─────────────────────────────────────────────────────
  {
    id: 'b2_49',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Wat zijn de twee soorten beenweefsel?',
    options: ['Hard en zacht', 'Compact en sponsachtig beenweefsel', 'Rood en wit beenweefsel', 'Binnen en buiten beenweefsel'],
    correct_answer: 'Compact en sponsachtig beenweefsel',
    explanation: 'Compact beenweefsel vormt de harde buitenkant. Sponsachtig beenweefsel zit in de uiteinden van pijpbeenderen en in platte botten (ribben, heupbeenderen).',
  },
  {
    id: 'b2_50',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Waar worden rode bloedcellen gemaakt?',
    options: ['In de spieren', 'In het rode beenmerg in sponsachtig beenweefsel', 'In de lever', 'In het kraakbeen'],
    correct_answer: 'In het rode beenmerg in sponsachtig beenweefsel',
    explanation: 'In de holten van het sponsachtig beenweefsel ligt het rode beenmerg. Dit beenmerg maakt rode bloedcellen aan.',
  },
  {
    id: 'b2_51',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Kalkstof zorgt voor de hardheid van bot. Lijmstof zorgt voor buigzaamheid. Wat gebeurt er als je ouder wordt?',
    options: ['Je botten krijgen meer lijmstof', 'Je botten bevatten minder lijmstof, waardoor ze breekbaarder worden', 'Je botten worden zachter', 'Er verandert niets'],
    correct_answer: 'Je botten bevatten minder lijmstof, waardoor ze breekbaarder worden',
    explanation: 'Als je jong bent heb je veel lijmstof (buigzaam). In de loop van je leven neemt de lijmstof af, waardoor botten breekbaarder worden.',
  },
  {
    id: 'b2_52',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Wat is de groeischijf?',
    options: ['De buitenkant van een bot', 'Een kraakbeenschijf tussen het langwerpige deel en de uiteinden van een pijpbeen, die beencellen aanmaakt', 'Een gewricht', 'Een tussenwervelschijf'],
    correct_answer: 'Een kraakbeenschijf tussen het langwerpige deel en de uiteinden van een pijpbeen, die beencellen aanmaakt',
    explanation: 'De groeischijf maakt beencellen aan waardoor je botten langer worden. Als je bent uitgegroeid (rond 21 bij jongens, eerder bij meisjes) verbeent de groeischijf.',
  },
  {
    id: 'b2_53',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Beenweefsel is opgebouwd uit beencellen en tussencelstof. Wat zit er in de tussencelstof?',
    options: ['Alleen water', 'Kalkstof en lijmstof', 'Spieren', 'Lucht'],
    correct_answer: 'Kalkstof en lijmstof',
    explanation: 'De tussencelstof bevat kalkstof (hardheid) en lijmstof (buigzaamheid). De combinatie maakt botten sterk.',
  },
  {
    id: 'b2_54',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Kraakbeenweefsel bestaat uit kraakbeencellen en buigzame tussencelstof met lijmstof. Waar vind je kraakbeen NIET?',
    options: ['In je gewrichten', 'In je oorschelp', 'In het puntje van je neus', 'In je spieren'],
    correct_answer: 'In je spieren',
    explanation: 'Kraakbeen zit in gewrichten, je oorschelp, het puntje van je neus, en de tussenwervelschijven. Niet in spieren.',
  },
  {
    id: 'b2_55',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Waarom lopen er veel bloedvaten door beenweefsel?',
    options: ['Om het bot warm te houden', 'Om bouwstoffen aan te voeren voor groei en herstel', 'Om het bot flexibel te maken', 'Dat is toeval'],
    correct_answer: 'Om bouwstoffen aan te voeren voor groei en herstel',
    explanation: 'Beencellen zorgen voor groei en herstel (ook bij botbreuken). Daarvoor hebben ze bouwstoffen nodig die via bloedvaten worden aangevoerd.',
  },

  // ── 4.7 Skeletten vergelijken ─────────────────────────────────────────────
  {
    id: 'b2_56',
    category: '4.7',
    sub_topic: 'skeletten_vergelijken',
    prompt: 'Dieren zonder skelet heten...',
    options: ['Gewervelde dieren', 'Ongewervelde dieren', 'Zoogdieren', 'Exoskelet-dieren'],
    correct_answer: 'Ongewervelde dieren',
    explanation: 'Ongewervelde dieren hebben geen skelet van botten. Voorbeelden: kwallen, wormen, naaktslakken. Ze krijgen stevigheid door water in hun lichaam.',
  },
  {
    id: 'b2_57',
    category: '4.7',
    sub_topic: 'skeletten_vergelijken',
    prompt: 'Wat is een exoskelet?',
    options: ['Een inwendig skelet', 'Een uitwendig skelet aan de buitenkant van het lichaam', 'Een kraakbeenskelet', 'Een skelet zonder botten'],
    correct_answer: 'Een uitwendig skelet aan de buitenkant van het lichaam',
    explanation: 'Een exoskelet zit aan de buitenkant van het dier. Het geeft stevigheid en bescherming tegen vijanden.',
  },
  {
    id: 'b2_58',
    category: '4.7',
    sub_topic: 'skeletten_vergelijken',
    prompt: 'Waaruit bestaat het exoskelet van weekdieren (slakken, schelpdieren)?',
    options: ['Chitine', 'Kalk', 'Bot', 'Kraakbeen'],
    correct_answer: 'Kalk',
    explanation: 'Weekdieren (huisjesslakken, schelpdieren) hebben een exoskelet van kalk. Insecten hebben chitine. Kreeftachtigen hebben kalk én chitine.',
  },
  {
    id: 'b2_59',
    category: '4.7',
    sub_topic: 'skeletten_vergelijken',
    prompt: 'Waaruit bestaat het exoskelet van insecten?',
    options: ['Kalk', 'Bot', 'Chitine', 'Lijmstof'],
    correct_answer: 'Chitine',
    explanation: 'Insecten hebben een exoskelet van chitine. Kreeftachtigen (krabben) hebben een exoskelet van kalk én chitine.',
  },
  {
    id: 'b2_60',
    category: '4.7',
    sub_topic: 'skeletten_vergelijken',
    prompt: 'Welke dieren zijn gewervelde dieren?',
    options: ['Insecten en spinnen', 'Vissen, amfibieën, reptielen, vogels en zoogdieren', 'Alleen zoogdieren', 'Weekdieren en wormen'],
    correct_answer: 'Vissen, amfibieën, reptielen, vogels en zoogdieren',
    explanation: 'Gewervelde dieren hebben een inwendig skelet van botten met een wervelkolom, schedel en ribben.',
  },
  {
    id: 'b2_61',
    category: '4.7',
    sub_topic: 'skeletten_vergelijken',
    prompt: 'Paarden en koeien zijn hoefgangers. Hoe lopen zij?',
    options: ['Op de hele voetzool', 'Op hun kootjes (tenen)', 'Alleen op de toppen van hun tenen, die eindigen in een hoef', 'Op hun hielen'],
    correct_answer: 'Alleen op de toppen van hun tenen, die eindigen in een hoef',
    explanation: 'Hoefgangers raken de grond alleen met de toppen van hun tenen. Hun middenvoetsbeentjes zijn lang, waardoor ze lange poten hebben en snel kunnen lopen.',
  },
  {
    id: 'b2_62',
    category: '4.7',
    sub_topic: 'skeletten_vergelijken',
    prompt: 'Honden en katten zijn teengangers. Beren en mensen zijn zoolgangers. Wat is het verschil?',
    options: ['Teengangers lopen op hun kootjes, zoolgangers op de hele voetzool', 'Zoolgangers zijn sneller', 'Teengangers hebben geen tenen', 'Er is geen verschil'],
    correct_answer: 'Teengangers lopen op hun kootjes, zoolgangers op de hele voetzool',
    explanation: 'Teengangers raken de grond met hun kootjes (poten zijn daardoor relatief lang → snel). Zoolgangers raken de grond met de hele voetzool (minder snel, wel goed afzetten).',
  },
  {
    id: 'b2_63',
    category: '4.7',
    sub_topic: 'skeletten_vergelijken',
    prompt: 'De voorste ledematen van een mens, kat, walvis en vleermuis lijken op elkaar. Welke botstukken hebben ze allemaal?',
    options: ['Alleen een opperarmbeen', 'Opperarmbeen, spaakbeen, ellepijp en handwortelbeentjes', 'Alleen vingers', 'Ze lijken niet op elkaar'],
    correct_answer: 'Opperarmbeen, spaakbeen, ellepijp en handwortelbeentjes',
    explanation: 'Alle onderarmen van zoogdieren bestaan uit een spaakbeen en een ellepijp. De botstructuur is vergelijkbaar, ook al zien de ledematen er heel anders uit (arm, poot, vin, vleugel).',
  },
  {
    id: 'b2_64',
    category: '4.7',
    sub_topic: 'skeletten_vergelijken',
    prompt: 'Een inktvis (zeekat) is een ongewerveld dier, maar heeft toch een inwendig skelet. Hoe kan dat?',
    options: ['Alle ongewervelden hebben een inwendig skelet', 'Het heeft een schelp in zijn lichaam (geen wervelkolom)', 'Het is eigenlijk een vis', 'Dat klopt niet'],
    correct_answer: 'Het heeft een schelp in zijn lichaam (geen wervelkolom)',
    explanation: 'Een inktvis heeft wel een inwendig skelet (een schelp/schulp), maar geen wervelkolom. Daarom is het toch een ongewerveld dier.',
  },

  // ── 4.1 Open vragen ──────────────────────────────────────────────────────────
  {
    id: 'bio2-open-1',
    type: 'open',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Noem de drie onderdelen die samenwerken bij bewegen.',
    correct_answer: 'Botten, spieren en gewrichten',
    explanation: 'Botten geven stevigheid, spieren zorgen voor de kracht, gewrichten zijn de scharnieren.',
  },
  {
    id: 'bio2-open-2',
    type: 'open',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Noem twee veranderingen die gebeuren als je regelmatig beweegt.',
    correct_answer: 'Spierkracht wordt groter en uithoudingsvermogen verbetert',
    explanation: 'Je spieren worden sterker en je longen nemen beter zuurstof op, waardoor je inspanning langer volhoudt.',
  },
  {
    id: 'bio2-open-3',
    type: 'open',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Waarom is bewegen goed voor je geestelijke gezondheid?',
    correct_answer: 'Door beweging komen er stoffen vrij in je lichaam die zorgen voor een goed humeur en minder stress',
    explanation: 'Bewegen is niet alleen goed voor je lijf, maar ook voor je hoofd.',
  },
  {
    id: 'bio2-open-4',
    type: 'open',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Wat is het verschil tussen spierkracht en uithoudingsvermogen?',
    correct_answer: 'Spierkracht = hoe sterk je spieren zijn. Uithoudingsvermogen = hoe lang je een inspanning kunt volhouden',
    explanation: 'Het zijn twee verschillende vormen van fitheid.',
  },
  {
    id: 'bio2-open-5',
    type: 'open',
    category: '4.1',
    sub_topic: 'fit_blijven',
    prompt: 'Noem drie eigenschappen van kraakbeen.',
    correct_answer: 'Elastisch, glad, bevat geen bloedvaten',
    explanation: 'Kraakbeen zit onder andere aan de uiteinden van botten en zorgt dat botten soepel langs elkaar bewegen.',
  },

  // ── 4.2 Open vragen ──────────────────────────────────────────────────────────
  {
    id: 'bio2-open-6',
    type: 'open',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Beschrijf de opbouw van een skeletspier van klein naar groot.',
    correct_answer: 'Celkernen → spiervezels → spierbundels → spier',
    explanation: 'Meerdere celkernen in een spiervezel, meerdere spiervezels in een spierbundel, meerdere spierbundels vormen samen een spier.',
  },
  {
    id: 'bio2-open-7',
    type: 'open',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wat zijn antagonisten? Geef een voorbeeld.',
    correct_answer: 'Twee spieren die tegengestelde bewegingen veroorzaken, bijvoorbeeld biceps en triceps',
    explanation: 'Biceps buigt de arm, triceps strekt de arm. Ze werken altijd tegengesteld.',
  },
  {
    id: 'bio2-open-8',
    type: 'open',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wat is de functie van pezen?',
    correct_answer: 'Pezen verbinden spieren met botten',
    explanation: 'Pezen zijn taai en sterk en kunnen niet samentrekken. Ze geven de trekkracht van de spier door aan het bot.',
  },
  {
    id: 'bio2-open-9',
    type: 'open',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Noem de drie soorten spieren en geef bij elk een eigenschap.',
    correct_answer: 'Skeletspieren (bewust aanspannen, aan botten), gladde spieren (onbewust, onvermoeibaar, in darmen/bloedvaten), hartspier (onbewust, onvermoeibaar)',
    explanation: 'Alleen skeletspieren kun je bewust aanspannen.',
  },
  {
    id: 'bio2-open-10',
    type: 'open',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wat is het verschil tussen snelle en langzame spiervezels?',
    correct_answer: 'Langzame spiervezels zijn rood en geschikt voor langdurige inspanning. Snelle spiervezels zijn wit/roze en geschikt voor korte, hevige inspanning',
    explanation: 'Eenden hebben veel langzame (rode) spiervezels omdat ze veel vliegen.',
  },
  {
    id: 'bio2-open-11',
    type: 'open',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Wat is de achillespees en waar zit deze?',
    correct_answer: 'De achillespees verbindt de kuitspier met het bot van de hiel',
    explanation: 'Deze pees trekt met veel kracht aan het hielbot als je loopt en springt.',
  },
  {
    id: 'bio2-open-12',
    type: 'open',
    category: '4.2',
    sub_topic: 'spieren_pezen',
    prompt: 'Hoe ontstaat kippenvel?',
    correct_answer: 'Aan elk lichaamshaartje zit een glad spiertje. Als al die spiertjes tegelijk samentrekken, gaan de haartjes overeind staan',
    explanation: 'Dit zijn gladde spiertjes die je niet bewust kunt aanspannen.',
  },

  // ── 4.3 Open vragen ──────────────────────────────────────────────────────────
  {
    id: 'bio2-open-13',
    type: 'open',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Noem de vier functies van het skelet.',
    correct_answer: '1) Beweging mogelijk maken samen met spieren, 2) Kwetsbare organen beschermen, 3) Stevigheid en vorm geven, 4) Rode bloedcellen aanmaken',
    explanation: 'Schedel beschermt hersenen, borstkas beschermt hart en longen.',
  },
  {
    id: 'bio2-open-14',
    type: 'open',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Uit welke drie soorten wervels bestaat de wervelkolom? Noem ze van boven naar beneden.',
    correct_answer: 'Halswervels, borstwervels, lendenwervels (daaronder heiligbeen en staartbeen)',
    explanation: 'Hoe lager de wervels, hoe groter ze zijn — ze moeten meer gewicht dragen.',
  },
  {
    id: 'bio2-open-15',
    type: 'open',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Waarom heeft de wervelkolom een dubbele S-vorm?',
    correct_answer: 'De dubbele S-vorm maakt de wervelkolom veerkrachtig en werkt als een schokdemper',
    explanation: 'Bij springen of lopen vangt de S-vorm een deel van de schok op.',
  },
  {
    id: 'bio2-open-16',
    type: 'open',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Wat zijn tussenwervelschijven en wat is hun functie?',
    correct_answer: 'Tussenwervelschijven zitten tussen de wervels. Ze helpen bij soepel bewegen en het opvangen van schokken',
    explanation: 'Ze zijn een kraakbeenverbinding.',
  },
  {
    id: 'bio2-open-17',
    type: 'open',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Waaruit bestaat de schoudergordel?',
    correct_answer: 'Twee schouderbladen en twee sleutelbeenderen',
    explanation: 'De schoudergordel zorgt dat je armen aan je romp vastzitten.',
  },
  {
    id: 'bio2-open-18',
    type: 'open',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Hoe onthoud je welk bot het spaakbeen is en welk de ellepijp?',
    correct_answer: 'Pink begint met een P, ellepijp eindigt met een P — de ellepijp zit aan de kant van je pink',
    explanation: 'Het spaakbeen zit aan de kant van je duim.',
  },
  {
    id: 'bio2-open-19',
    type: 'open',
    category: '4.3',
    sub_topic: 'skelet',
    prompt: 'Wat is bijzonder aan de onderkaak vergeleken met de andere schedelbotten?',
    correct_answer: 'De onderkaak is het enige niet-vergroeide bot van de schedel — het zit los, zodat je kunt bijten en kauwen',
    explanation: 'Alle andere schedelbotten zitten stevig aan elkaar vast.',
  },

  // ── 4.4 Open vragen ──────────────────────────────────────────────────────────
  {
    id: 'bio2-open-20',
    type: 'open',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Noem drie soorten gewrichten en geef bij elk een voorbeeld.',
    correct_answer: 'Kogelgewricht (schouder, heup) = alle richtingen. Scharniergewricht (knie, elleboog) = buigen/strekken. Rolgewricht (bij elleboog) = hand draaien',
    explanation: 'Dit zijn niet de enige soorten gewrichten, maar wel de drie belangrijkste.',
  },
  {
    id: 'bio2-open-21',
    type: 'open',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Noem vier onderdelen van een gewricht.',
    correct_answer: 'Gewrichtskom, gewrichtskop, kraakbeen, gewrichtssmeer, gewrichtskapsel, gewrichtsbanden (4 van deze 6)',
    explanation: 'De gewrichtskom is de holte, de gewrichtskop is de ronding die erin past.',
  },
  {
    id: 'bio2-open-22',
    type: 'open',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Wat is het verschil tussen een kraakbeenverbinding en een naadverbinding?',
    correct_answer: 'Kraakbeenverbinding (tussenwervelschijf) = buigzaam, beperkte beweging. Naadverbinding (schedel) = stevig vast, geen beweging',
    explanation: 'Bij een naadverbinding zitten de botten met gekartelde randen aan elkaar vast.',
  },
  {
    id: 'bio2-open-23',
    type: 'open',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Wat zijn fontanellen?',
    correct_answer: 'Zachte plekken in de schedel van een baby waar de schedelbotten nog niet aan elkaar vastzitten',
    explanation: 'Stevig weefsel beschermt de hersenen. Na 12-18 maanden groeien de botten dicht.',
  },
  {
    id: 'bio2-open-24',
    type: 'open',
    category: '4.4',
    sub_topic: 'botverbindingen',
    prompt: 'Waarvoor dient gewrichtssmeer?',
    correct_answer: 'Gewrichtssmeer zorgt dat het kraakbeen glad blijft, het gewricht soepel werkt en slijtage wordt voorkomen',
    explanation: 'Zonder gewrichtssmeer zou het kraakbeen snel slijten.',
  },

  // ── 4.6 Open vragen ──────────────────────────────────────────────────────────
  {
    id: 'bio2-open-25',
    type: 'open',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Wat zijn de twee soorten beenweefsel en waar zitten ze?',
    correct_answer: 'Compact beenweefsel = harde buitenkant van elk bot, vooral bij pijpbeenderen. Sponsachtig beenweefsel = in de uiteinden van pijpbeenderen en in platte botten',
    explanation: 'In het sponsachtig beenweefsel zit het rode beenmerg.',
  },
  {
    id: 'bio2-open-26',
    type: 'open',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Waar worden rode bloedcellen gemaakt?',
    correct_answer: 'In het rode beenmerg, dat in de holten van het sponsachtig beenweefsel ligt',
    explanation: 'Dit is een van de vier functies van het skelet.',
  },
  {
    id: 'bio2-open-27',
    type: 'open',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Wat doet kalkstof en wat doet lijmstof in botten?',
    correct_answer: 'Kalkstof zorgt voor de hardheid van bot. Lijmstof zorgt voor buigzaamheid',
    explanation: 'De combinatie maakt botten sterk. Met de leeftijd neemt lijmstof af, waardoor botten breekbaarder worden.',
  },
  {
    id: 'bio2-open-28',
    type: 'open',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Wat is de groeischijf en wat doet deze?',
    correct_answer: 'De groeischijf is een kraakbeenschijf in een pijpbeen die beencellen aanmaakt, waardoor het bot langer wordt',
    explanation: 'Als je bent uitgegroeid (rond 21 jaar bij jongens) verbeent de groeischijf.',
  },
  {
    id: 'bio2-open-29',
    type: 'open',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Waarom lopen er veel bloedvaten door beenweefsel?',
    correct_answer: 'Om bouwstoffen aan te voeren voor groei en herstel van het bot',
    explanation: 'Beencellen zorgen voor groei en ook voor herstel als een bot breekt.',
  },
  {
    id: 'bio2-open-30',
    type: 'open',
    category: '4.6',
    sub_topic: 'steunweefsels',
    prompt: 'Noem twee verschillen tussen kraakbeen en bot.',
    correct_answer: 'Kraakbeen bevat geen bloedvaten (bot wel). Kraakbeen is elastisch en glad (bot is hard)',
    explanation: 'Kraakbeen zit in gewrichten, neus, oren en tussenwervelschijven.',
  },
];
