export const bondingQuestions: string[] = [
  "Welke superkracht zou je kiezen voor 1 dag — en wat is het eerste wat je ermee doet?",
  "Als je 1 miljoen euro zou krijgen, wat is het allereerste wat jij koopt?",
  "Pineapple op pizza: voor of tegen? Verdedig je keuze 😤",
  "Welke 3 dingen neem je mee naar een onbewoond eiland?",
  "Wat is het stomste advies dat iemand jou ooit heeft gegeven?",
  "Welke serie of film MOET iedereen volgens jou zien?",
  "Welk dier zou jij willen zijn voor één dag?",
  "Als jij 1 wet mocht maken voor heel Nederland, wat zou die zijn?",
  "Wat is het raarste eten dat je ooit hebt geprobeerd?",
  "Welke uitvinding mag wat jou betreft meteen verdwijnen?",
  "Heb je een geheim talent dat bijna niemand weet?",
  "Welk geluid haat jij het meest in de wereld?",
  "Als jij een videogame karakter mocht zijn, welke?",
  "Als jij een YouTube of TikTok kanaal had, waar zou het over gaan?",
  "Wat is de slechtste film die je ooit hebt gezien?",
  "Hot dog of hamburger? Geen halve antwoorden, kies!",
  "Zomer of winter? Waarom?",
  "Wat is het meest random feitje dat jij weet?",
  "Welke skill zou jij in 5 seconden willen leren?",
  "Welk land zou je willen bezoeken, en wat is het eerste dat je daar gaat doen?",
  "Als jij een eigen restaurant had, wat staat er op het menu?",
  "iPhone of Android? Verdedig je keuze met je leven 📱",
  "Wat is de meest random droom die je ooit hebt gehad?",
  "Welk woord vind jij echt irritant?",
  "Liever praten met dieren of met aliens?",
  "Wat is jouw ultieme comfort food?",
  "Tijdmachine: terug of vooruit in de tijd? En waarheen?",
  "Wat is iets dat je deze week hebt gezien dat je leuk vond?",
  "Welke 3 emoji's beschrijven jou het best? 🤔",
  "Als jij voor 1 dag een ander persoon mocht zijn (echt of fictief), wie?"
];
