export const bondingQuestions: string[] = [
  "Welke superkracht zou je kiezen voor 1 dag — en wat is het eerste wat je ermee doet?",
  "Als je 1 miljoen euro zou krijgen, wat is het allereerste wat jij koopt?",
  "Pineapple op pizza: voor of tegen? Verdedig je keuze 😤",
  "Welke 3 dingen neem je mee naar een onbewoond eiland?",
  "Wat is het stomste advies dat iemand jou ooit heeft gegeven?",
  "Welke serie of film MOET iedereen volgens jou zien?",
  "Welk dier zou jij willen zijn voor één dag?",
  "Als jij 1 wet mocht maken voor heel Nederland, wat zou die zijn?",
  "Wat is het raarste eten dat je ooit hebt geprobeerd?",
  "Welke uitvinding mag wat jou betreft meteen verdwijnen?",
  "Heb je een geheim talent dat bijna niemand weet?",
  "Welk geluid haat jij het meest in de wereld?",
  "Als jij een videogame karakter mocht zijn, welke?",
  "Als jij een YouTube of TikTok kanaal had, waar zou het over gaan?",
  "Wat is de slechtste film die je ooit hebt gezien?",
  "Hot dog of hamburger? Geen halve antwoorden, kies!",
  "Zomer of winter? Waarom?",
  "Wat is het meest random feitje dat jij weet?",
  "Welke skill zou jij in 5 seconden willen leren?",
  "Welk land zou je willen bezoeken, en wat is het eerste dat je daar gaat doen?",
  "Als jij een eigen restaurant had, wat staat er op het menu?",
  "iPhone of Android? Verdedig je keuze met je leven 📱",
  "Wat is de meest random droom die je ooit hebt gehad?",
  "Welk woord vind jij echt irritant?",
  "Liever praten met dieren of met aliens?",
  "Wat is jouw ultieme comfort food?",
  "Tijdmachine: terug of vooruit in de tijd? En waarheen?",
  "Wat is iets dat je deze week hebt gezien dat je leuk vond?",
  "Welke 3 emoji's beschrijven jou het best? 🤔",
  "Als jij voor 1 dag een ander persoon mocht zijn (echt of fictief), wie?",
  "100 eend-grote paarden of 1 paard-grote eend — wat versla je liever? 🦆",
  "Zombie-apocalyps: welke 3 mensen (echt of beroemd) wil je in je team?",
  "Welke superkracht klinkt cool maar is eigenlijk best waardeloos?",
  "Als je maar 1 gerecht voor de rest van je leven mocht eten, wat wordt het?",
  "Welk dier zou het engst zijn als het zo groot was als een hond?",
  "Wat is de meest nutteloze skill waar jij stiekem best goed in bent?",
  "Beste fastfood — geef je top 3.",
  "Als je je eigen land mocht stichten: hoe heet het en wat is regel nummer 1?",
  "Vliegen of onzichtbaar zijn? En eerlijk: wat ga je er ÉCHT mee doen?",
  "Eén game voor de rest van je leven — welke kies je?",
  "Wat is het meest random dat je ooit hebt opgezocht op internet?",
  "Als jij 1 dag de baas van school was, wat verander je als eerste?",
  "Pizza, patat of pasta — kies er één voor altijd.",
  "Als dieren konden praten, welk dier zou het meest irritant zijn?",
  "Wat is een mening van jou waar bijna niemand het mee eens is?",
  "Welke film of serie heb je het vaakst gekeken?",
  "Welk 'onmogelijk' huisdier zou je willen: tijger, dolfijn of draak?",
  "Wat is het beste cadeau dat je ooit hebt gekregen?",
  "Wat is erger: een week zonder telefoon of een week zonder warm water?",
  "Welk nummer staat nu het meest op repeat bij jou?",
  "Eén ding gratis voor altijd — eten, kleding of games?",
  "Wat is het grappigste dat ooit op school is gebeurd?",
  "Welke YouTuber of streamer kijk je het liefst?",
  "Als je 24 uur lang niet betrapt kon worden, wat zou je doen? 😈",
  "Welke eten-combi vind jij lekker maar iedereen vies?",
  "Als je tijd kon stilzetten, wat is het eerste wat je doet?",
  "Welk game- of filmkarakter zou je in het echt willen zijn?"
];
