// SQL to run in Supabase:
//
// create table if not exists dnh_wiskunde_attempts (
//   id uuid default gen_random_uuid() primary key,
//   question_id text not null,
//   question_text text not null,
//   student_answer text not null,
//   correct_answer text not null,
//   is_correct boolean not null,
//   category text not null,
//   sub_topic text not null,
//   created_at timestamptz default now()
// );
//
// create table if not exists dnh_wiskunde_herhaling (
//   id uuid default gen_random_uuid() primary key,
//   question_id text not null unique,
//   question_text text not null,
//   correct_answer text not null,
//   category text not null,
//   sub_topic text not null,
//   times_correct integer default 0,
//   created_at timestamptz default now()
// );

export type WiskundeQuestion = {
  id: string;
  type: 'multiple_choice' | 'numeric_input';
  category: 'H8' | 'H9';
  sub_topic: string;
  prompt: string;
  options?: string[];
  correct_answer: string;
  tolerance?: number;
  explanation: string;
  hint?: string;
};

export const SUB_TOPIC_LABELS: Record<string, string> = {
  regelmaat: '8.1 Regelmaat',
  grafieken: '8.2 Grafieken',
  grafiek_bij_formule: '8.3 Grafiek bij formule',
  formules_veranderen: '8.4 Formules veranderen',
  formule_bij_grafiek: '8.5 Formule bij grafiek',
  formule_bij_tabel: '8.6 Formule bij tabel',
  lijnsymmetrie: '9.1 Lijnsymmetrie',
  puntsymmetrie: '9.3 Puntsymmetrie',
  vlakke_figuren: '9.4 Vlakke figuren',
  hoeken_berekenen: '9.7 Hoeken berekenen',
};

export const WISKUNDE_QUESTIONS: WiskundeQuestion[] = [
  // ── H8 · 8.1 Regelmaat ──────────────────────────────────────────────
  {
    id: 'h8_reg_1',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'regelmaat',
    prompt: 'In de tabel van Eva stijgen de inkomsten met €3 per uur. De inkomsten bij 0 uur zijn €4,50. Wat zijn de inkomsten bij 3 uur?',
    options: ['€12,00', '€13,50', '€15,00', '€10,50'],
    correct_answer: '€13,50',
    explanation: 'Bij 0 uur: €4,50. Per uur +€3. Na 3 uur: 4,50 + 3×3 = 4,50 + 9 = €13,50',
  },
  {
    id: 'h8_reg_2',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'regelmaat',
    prompt: 'Een tabel heeft regelmaat. Bij 0 uur is het bedrag €5. Per uur komt er €7,50 bij. Wat is het bedrag bij 4 uur? (geef alleen het getal)',
    correct_answer: '35',
    explanation: '5 + 4 × 7,50 = 5 + 30 = €35',
  },
  {
    id: 'h8_reg_3',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'regelmaat',
    prompt: "Wat betekent 'regelmaat' in een tabel?",
    options: [
      'De getallen worden steeds groter',
      'Er komt steeds hetzelfde bedrag bij',
      'De tabel heeft 4 kolommen',
      'De getallen zijn allemaal even',
    ],
    correct_answer: 'Er komt steeds hetzelfde bedrag bij',
    explanation: 'Regelmaat = steeds hetzelfde verschil tussen opeenvolgende waarden',
  },
  {
    id: 'h8_reg_4',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'regelmaat',
    prompt: 'In een tabel komt er per uur €6 bij. Bij 0 uur is het bedrag €8. Hoeveel is het bij 5 uur? (geef alleen het getal)',
    correct_answer: '38',
    explanation: '8 + 5 × 6 = 8 + 30 = 38',
  },

  // ── H8 · 8.2 Grafieken ──────────────────────────────────────────────
  {
    id: 'h8_graf_1',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'grafieken',
    prompt: 'Hanneke verdient €5 reiskostenvergoeding plus €7,50 per uur. Wat is het punt op de y-as van haar grafiek?',
    options: ['(0, 7,50)', '(0, 5)', '(1, 12,50)', '(0, 0)'],
    correct_answer: '(0, 5)',
    explanation: 'Bij 0 uur verdient ze alleen de reiskostenvergoeding: €5. Dat is het startpunt op de y-as.',
  },
  {
    id: 'h8_graf_2',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'grafieken',
    prompt: 'Een grafiek bij een tabel met regelmaat is altijd een...',
    options: ['Kromme lijn', 'Rechte lijn', 'Cirkel', 'Gebroken lijn'],
    correct_answer: 'Rechte lijn',
    explanation: 'Bij regelmaat (steeds hetzelfde verschil) krijg je altijd een rechte lijn.',
  },
  {
    id: 'h8_graf_3',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'grafieken',
    prompt: 'Hanneke: reiskostenvergoeding €5, per uur €7,50. Hoeveel verdient ze na 3 uur? (geef alleen het getal)',
    correct_answer: '27.5',
    tolerance: 0.5,
    explanation: '5 + 3 × 7,50 = 5 + 22,50 = €27,50',
  },

  // ── H8 · 8.3 Grafiek bij een formule ────────────────────────────────
  {
    id: 'h8_gbf_1',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'grafiek_bij_formule',
    prompt: 'Bij de formule prijs (€) = 12 + 3a, wat is het begingetal?',
    options: ['3', '12', 'a', '15'],
    correct_answer: '12',
    explanation: 'Het begingetal is het getal dat er staat zonder variabele: 12. Dit is waar de grafiek de y-as snijdt.',
  },
  {
    id: 'h8_gbf_2',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'grafiek_bij_formule',
    prompt: 'Bij de formule prijs (€) = 12 + 3a, wat is het stijggetal?',
    options: ['12', '3', 'a', '15'],
    correct_answer: '3',
    explanation: 'Het stijggetal staat voor de variabele (×a). Per foto komt er €3 bij.',
  },
  {
    id: 'h8_gbf_3',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'grafiek_bij_formule',
    prompt: 'Wat zijn de variabelen in de formule prijs (€) = 12 + 3a?',
    options: ['Alleen prijs', 'Alleen a', 'prijs en a', '12 en 3'],
    correct_answer: 'prijs en a',
    explanation: 'De variabelen zijn de waarden die veranderen: prijs (links van =) en a (rechts).',
  },
  {
    id: 'h8_gbf_4',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'grafiek_bij_formule',
    prompt: 'Formule: prijs (€) = 12 + 3a. Wat is de prijs als a = 5? (geef alleen het getal)',
    correct_answer: '27',
    explanation: '12 + 3 × 5 = 12 + 15 = 27',
  },
  {
    id: 'h8_gbf_5',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'grafiek_bij_formule',
    prompt: 'Een grafiek daalt. Welk getal hoort bij de formule?',
    options: ['Stijggetal', 'Begingetal', 'Daalgetal', 'Variabele'],
    correct_answer: 'Daalgetal',
    explanation: 'Bij een dalende grafiek heet het getal voor de variabele het daalgetal.',
  },
  {
    id: 'h8_gbf_6',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'grafiek_bij_formule',
    prompt: 'Formule: tankinhoud (liters) = 140 − 0,8a. Hoeveel liter zit er in de tank na 50 km? (geef alleen het getal)',
    correct_answer: '100',
    explanation: '140 − 0,8 × 50 = 140 − 40 = 100 liter',
  },
  {
    id: 'h8_gbf_7',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'grafiek_bij_formule',
    prompt: 'Formule: tankinhoud (liters) = 140 − 0,8a. Na hoeveel km is de tank leeg (= 0 liter)? (geef alleen het getal)',
    correct_answer: '175',
    explanation: '0 = 140 − 0,8a → 0,8a = 140 → a = 140 ÷ 0,8 = 175 km',
  },
  {
    id: 'h8_gbf_8',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'grafiek_bij_formule',
    prompt: 'De formule is inhoud = 80 − 0,15a. Wat is het daalgetal?',
    options: ['80', '0,15', '−0,15', 'a'],
    correct_answer: '0,15',
    explanation: 'Het daalgetal is 0,15. Per km gaat er 0,15 liter uit de tank.',
  },
  {
    id: 'h8_gbf_9',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'grafiek_bij_formule',
    prompt: 'Formule: inhoud (liters) = 80 − 0,15a. Wat is de inhoud bij a = 200? (geef alleen het getal)',
    correct_answer: '50',
    explanation: '80 − 0,15 × 200 = 80 − 30 = 50 liter',
  },

  // ── H8 · 8.4 Formules veranderen ────────────────────────────────────
  {
    id: 'h8_fv_1',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'formules_veranderen',
    prompt: 'De formule is reistegoed (€) = 5,60 − 0,15k. Naomi waardeert haar tegoed op met €20. Wat is het nieuwe begingetal?',
    options: ['€25,60', '€20,00', '€5,60', '€20,15'],
    correct_answer: '€25,60',
    explanation: 'Oud begingetal 5,60 + opwaardering 20 = nieuw begingetal 25,60',
  },
  {
    id: 'h8_fv_2',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'formules_veranderen',
    prompt: 'De formule is reistegoed (€) = 5,60 − 0,15k. De kilometerprijs wordt €0,03 lager. Wat is het nieuwe daalgetal?',
    options: ['0,18', '0,12', '0,03', '0,15'],
    correct_answer: '0,12',
    explanation: 'Oud daalgetal 0,15 − verlaging 0,03 = nieuw daalgetal 0,12',
  },
  {
    id: 'h8_fv_3',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'formules_veranderen',
    prompt: 'Oude formule: reistegoed = 5,60 − 0,15k. Na opwaardering +€20 en kilometerprijs −€0,03: wat is het reistegoed na 100 km met de NIEUWE formule? (geef alleen het getal)',
    correct_answer: '13.6',
    tolerance: 0.1,
    explanation: 'Nieuwe formule: 25,60 − 0,12k. Bij k=100: 25,60 − 0,12×100 = 25,60 − 12 = €13,60',
  },

  // ── H8 · 8.5 Formule maken bij een grafiek ──────────────────────────
  {
    id: 'h8_fbg_1',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'formule_bij_grafiek',
    prompt: 'Een grafiek van een spaarrekening begint bij €2000 en stijgt €500 per jaar. Wat is het bedrag na 3 jaar? (geef alleen het getal)',
    correct_answer: '3500',
    explanation: '2000 + 500 × 3 = 2000 + 1500 = €3500',
  },
  {
    id: 'h8_fbg_2',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'formule_bij_grafiek',
    prompt: 'Je leest een grafiek af. Bij t=0 is het bedrag €2000, bij t=1 is het €2500. Wat is het stijggetal?',
    options: ['2000', '2500', '500', '1'],
    correct_answer: '500',
    explanation: 'Stijggetal = verschil ÷ stappen = (2500 − 2000) ÷ 1 = 500 per jaar',
  },
  {
    id: 'h8_fbg_3',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'formule_bij_grafiek',
    prompt: 'Hoe bepaal je het begingetal uit een grafiek?',
    options: [
      'Waar de lijn de x-as snijdt',
      'Waar de lijn de y-as snijdt',
      'Het hoogste punt',
      'Het laagste punt',
    ],
    correct_answer: 'Waar de lijn de y-as snijdt',
    explanation: 'Het begingetal is de waarde op de y-as, dus waar de horizontale variabele = 0.',
  },
  {
    id: 'h8_fbg_4',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'formule_bij_grafiek',
    prompt: 'Uit een grafiek lees je af: bij t=0 is het bedrag €10, bij t=5 is het €40. Wat is het stijggetal? (geef alleen het getal)',
    correct_answer: '6',
    explanation: '(40 − 10) ÷ 5 = 30 ÷ 5 = 6 per dag',
  },
  {
    id: 'h8_fbg_5',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'formule_bij_grafiek',
    prompt: 'Een grafiek DAALT. Twee punten: (0, 60) en (4, 40). Hoe bereken je het daalgetal?',
    options: [
      '(60−40) ÷ 4 = 5',
      '(40−60) ÷ 4 = −5',
      '60 ÷ 4 = 15',
      '40 ÷ 60 = 0,67',
    ],
    correct_answer: '(60−40) ÷ 4 = 5',
    explanation: 'Daalgetal = verschil ÷ stappen = (60−40) ÷ 4 = 20 ÷ 4 = 5. Het daalgetal is altijd positief, de min zit al in de formule.',
  },

  // ── H8 · 8.6 Formule maken bij een tabel ────────────────────────────
  {
    id: 'h8_fbt_1',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'formule_bij_tabel',
    prompt: 'Tabel FIETSTOCHT: bij t=0 is afstand 450m, bij t=5 is afstand 1250m. Hoeveel meter per minuut? (geef alleen het getal)',
    correct_answer: '160',
    explanation: '(1250 − 450) ÷ 5 = 800 ÷ 5 = 160 meter per minuut',
  },
  {
    id: 'h8_fbt_2',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'formule_bij_tabel',
    prompt: 'Bij een tabel: t=0 → 450m, t=5 → 1250m, t=10 → 2050m. Wat is de formule?',
    options: [
      'afstand = 450 + 160t',
      'afstand = 160 + 450t',
      'afstand = 1250 + 160t',
      'afstand = 450 × 160t',
    ],
    correct_answer: 'afstand = 450 + 160t',
    explanation: 'Begingetal = 450 (waarde bij t=0). Stijggetal = 160 (per minuut). Formule = 450 + 160t',
  },
  {
    id: 'h8_fbt_3',
    type: 'numeric_input',
    category: 'H8',
    sub_topic: 'formule_bij_tabel',
    prompt: 'Tabel: bij t=0 afstand = 450m. Per minuut 160m erbij. Wat is de afstand na 15 minuten? (geef alleen het getal)',
    correct_answer: '2850',
    explanation: '450 + 160 × 15 = 450 + 2400 = 2850 meter',
  },
  {
    id: 'h8_fbt_4',
    type: 'multiple_choice',
    category: 'H8',
    sub_topic: 'formule_bij_tabel',
    prompt: 'Hoe vind je het begingetal uit een tabel?',
    options: [
      'De grootste waarde in de tabel',
      'De waarde bij de variabele = 0',
      'Het verschil tussen twee waarden',
      'De eerste kolom',
    ],
    correct_answer: 'De waarde bij de variabele = 0',
    explanation: 'Het begingetal staat onder de 0 in de tabel — het is de startwaarde.',
  },

  // ── H9 · 9.1 Lijnsymmetrie ──────────────────────────────────────────
  {
    id: 'h9_ls_1',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'lijnsymmetrie',
    prompt: 'Wat is lijnsymmetrie?',
    options: [
      'Een figuur die je kunt draaien',
      'Een figuur die je in twee gelijke helften kunt vouwen',
      'Een figuur met rechte hoeken',
      'Een figuur met gelijke zijden',
    ],
    correct_answer: 'Een figuur die je in twee gelijke helften kunt vouwen',
    explanation: 'Bij lijnsymmetrie kun je de figuur langs de symmetrieas vouwen en vallen beide helften precies op elkaar.',
  },
  {
    id: 'h9_ls_2',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'lijnsymmetrie',
    prompt: "Je spiegelt driehoek ABC in een lijn s. Hoe heet het spiegelbeeld?",
    options: ["ABC", "A'B'C'", "CBA", "A₁B₁C₁"],
    correct_answer: "A'B'C'",
    explanation: "Het spiegelbeeld krijgt dezelfde letters met een accent (streepje): A', B', C'.",
  },
  {
    id: 'h9_ls_3',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'lijnsymmetrie',
    prompt: "Bij spiegelen in een lijn geldt: het spiegelbeeld A' ligt...",
    options: [
      'Op de spiegellijn',
      'Even ver van de spiegellijn als A, aan de andere kant',
      'Twee keer zo ver als A',
      'Altijd rechts van A',
    ],
    correct_answer: 'Even ver van de spiegellijn als A, aan de andere kant',
    explanation: "Bij spiegelen ligt elk punt even ver van de spiegellijn, maar aan de andere kant. De lijn AA' staat loodrecht op de spiegellijn.",
  },
  {
    id: 'h9_ls_4',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'lijnsymmetrie',
    prompt: 'Welk hulpmiddel gebruik je om te spiegelen in een lijn?',
    options: ['Liniaal', 'Passer', 'Geodriehoek (met de loodlijn)', 'Gradenboog'],
    correct_answer: 'Geodriehoek (met de loodlijn)',
    explanation: 'Je legt de geodriehoek met de loodlijn op de spiegellijn om de juiste afstand aan de andere kant te meten.',
  },

  // ── H9 · 9.3 Puntsymmetrie ──────────────────────────────────────────
  {
    id: 'h9_ps_1',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'puntsymmetrie',
    prompt: 'Wat is puntsymmetrie?',
    options: [
      'Spiegelen in een lijn',
      'Draaien om een punt over 90°',
      'Draaien om een punt over 180°',
      'Verschuiven over een afstand',
    ],
    correct_answer: 'Draaien om een punt over 180°',
    explanation: 'Puntsymmetrie = draaisymmetrie met een draaihoek van 180°. Het punt is het centrum.',
  },
  {
    id: 'h9_ps_2',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'puntsymmetrie',
    prompt: 'In een zeshoek is punt M het middelpunt. M is het midden van lijnstuk AD, BE en CF. Hoe heet M?',
    options: ['Het snijpunt', 'Het punt van symmetrie', 'De tophoek', 'Het zwaartepunt'],
    correct_answer: 'Het punt van symmetrie',
    explanation: 'M is het punt van symmetrie (= centrum) omdat elk lijnstuk door M de figuur in twee gelijke delen verdeelt.',
  },
  {
    id: 'h9_ps_3',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'puntsymmetrie',
    prompt: "Bij spiegelen in een punt P geldt: A' ligt...",
    options: [
      'Naast A',
      'Even ver van P als A, maar aan de andere kant van P',
      'Op punt P',
      'Twee keer zo ver van P',
    ],
    correct_answer: 'Even ver van P als A, maar aan de andere kant van P',
    explanation: "Bij puntspiegeling trek je een lijn van A door P. A' ligt even ver van P als A, maar aan de andere kant.",
  },
  {
    id: 'h9_ps_4',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'puntsymmetrie',
    prompt: 'Puntsymmetrie is hetzelfde als draaisymmetrie met een draaihoek van...',
    options: ['90°', '120°', '180°', '360°'],
    correct_answer: '180°',
    explanation: 'Puntsymmetrie = draaisymmetrie met draaihoek 180°.',
  },

  // ── H9 · 9.4 Symmetrie in vlakke figuren ────────────────────────────
  {
    id: 'h9_vf_1',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'vlakke_figuren',
    prompt: 'Hoeveel symmetrieassen heeft een vierkant?',
    options: ['2', '3', '4', '8'],
    correct_answer: '4',
    explanation: 'Een vierkant heeft 4 symmetrieassen: 2 door de middens van tegenoverliggende zijden, 2 door de hoekpunten.',
  },
  {
    id: 'h9_vf_2',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'vlakke_figuren',
    prompt: 'Een gelijkbenige driehoek heeft...',
    options: [
      'Geen symmetrieassen',
      '1 symmetrieas',
      '2 symmetrieassen',
      '3 symmetrieassen',
    ],
    correct_answer: '1 symmetrieas',
    explanation: 'Een gelijkbenige driehoek (2 gelijke zijden) heeft 1 symmetrieas: van de tophoek naar het midden van de basis.',
  },
  {
    id: 'h9_vf_3',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'vlakke_figuren',
    prompt: 'Bij een gelijkbenige driehoek PQR met PR = QR heten hoek P en hoek Q de...',
    options: ['Tophoeken', 'Basishoeken', 'Rechte hoeken', 'Overstaande hoeken'],
    correct_answer: 'Basishoeken',
    explanation: 'De twee gelijke hoeken bij de basis heten basishoeken. Hoek R (bij de top) heet de tophoek.',
  },
  {
    id: 'h9_vf_4',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'vlakke_figuren',
    prompt: 'In vierkant ABCD: welke zijden zijn evenwijdig?',
    options: ['AB en BC', 'AB en CD', 'AB en AD', 'Geen'],
    correct_answer: 'AB en CD',
    explanation: 'In een vierkant zijn tegenoverliggende zijden evenwijdig: AB // CD en AD // BC.',
  },
  {
    id: 'h9_vf_5',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'vlakke_figuren',
    prompt: 'Alle hoeken van een vierkant zijn...',
    options: ['60°', '90°', '120°', '180°'],
    correct_answer: '90°',
    explanation: 'Een vierkant heeft 4 rechte hoeken van elk 90°. Dat herken je aan de rechtehoektekens.',
  },

  // ── H9 · 9.7 Hoeken berekenen ───────────────────────────────────────
  {
    id: 'h9_hb_1',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'hoeken_berekenen',
    prompt: 'Twee lijnen snijden elkaar. Hoek A₁ = 121°. Wat is hoek A₃ (de overstaande hoek)?',
    options: ['59°', '121°', '180°', '90°'],
    correct_answer: '121°',
    explanation: 'Overstaande hoeken zijn gelijk. A₁ en A₃ liggen tegenover elkaar, dus A₃ = A₁ = 121°.',
  },
  {
    id: 'h9_hb_2',
    type: 'numeric_input',
    category: 'H9',
    sub_topic: 'hoeken_berekenen',
    prompt: 'Twee lijnen snijden elkaar. Hoek A₁ = 121°. Bereken hoek A₂. (geef alleen het getal)',
    correct_answer: '59',
    explanation: 'A₁ en A₂ zijn samen een gestrekte hoek: 180°. Dus A₂ = 180 − 121 = 59°',
  },
  {
    id: 'h9_hb_3',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'hoeken_berekenen',
    prompt: 'Wat zijn overstaande hoeken?',
    options: [
      'Hoeken die naast elkaar liggen',
      'Hoeken die tegenover elkaar liggen bij een snijpunt',
      'Hoeken van 90°',
      'Hoeken in een driehoek',
    ],
    correct_answer: 'Hoeken die tegenover elkaar liggen bij een snijpunt',
    explanation: 'Overstaande hoeken liggen tegenover elkaar bij het snijpunt van twee lijnen. Ze zijn altijd even groot.',
  },
  {
    id: 'h9_hb_4',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'hoeken_berekenen',
    prompt: 'Een gestrekte hoek is...',
    options: ['90°', '120°', '180°', '360°'],
    correct_answer: '180°',
    explanation: 'Een gestrekte hoek = twee hoeken die samen op een rechte lijn liggen = 180°.',
  },
  {
    id: 'h9_hb_5',
    type: 'numeric_input',
    category: 'H9',
    sub_topic: 'hoeken_berekenen',
    prompt: 'Twee lijnen snijden elkaar. Eén hoek is 73°. Hoe groot is de hoek ernaast? (geef alleen het getal)',
    correct_answer: '107',
    explanation: 'Gestrekte hoek = 180°. De hoek ernaast = 180 − 73 = 107°',
  },
  {
    id: 'h9_hb_6',
    type: 'numeric_input',
    category: 'H9',
    sub_topic: 'hoeken_berekenen',
    prompt: 'Lijn c // lijn d. Bij punt W is hoek W₁ = 65°. Hoek V₄ bij punt V op lijn d is even groot als W₁ (schuifsymmetrie). Hoe groot is hoek V₄? (geef alleen het getal)',
    correct_answer: '65',
    explanation: 'Bij evenwijdige lijnen en schuifsymmetrie: W₁ = V₄ = 65°',
  },
  {
    id: 'h9_hb_7',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'hoeken_berekenen',
    prompt: 'c // d. De hoeken bij W schuif je naar V. Wat klopt er?',
    options: ['W₁ = V₁', 'W₁ = V₄', 'W₁ = V₂', 'Geen van deze'],
    correct_answer: 'W₁ = V₄',
    explanation: 'Door schuifsymmetrie bij evenwijdige lijnen: W₁ = V₄ en W₂ = V₁ (niet W₁ = V₁!).',
  },
  {
    id: 'h9_hb_8',
    type: 'numeric_input',
    category: 'H9',
    sub_topic: 'hoeken_berekenen',
    prompt: 'In een gelijkbenige driehoek is de tophoek 96°. Hoe groot is één basishoek? (geef alleen het getal)',
    correct_answer: '42',
    explanation: 'Hoekensom driehoek = 180°. Twee basishoeken zijn gelijk. (180 − 96) ÷ 2 = 84 ÷ 2 = 42°',
  },
  {
    id: 'h9_hb_9',
    type: 'multiple_choice',
    category: 'H9',
    sub_topic: 'hoeken_berekenen',
    prompt: 'Bij het berekenen van hoeken moet je altijd...',
    options: [
      'Een tekening maken',
      'De berekening EN de gebruikte regel opschrijven',
      'Een geodriehoek gebruiken',
      'Alle hoeken meten',
    ],
    correct_answer: 'De berekening EN de gebruikte regel opschrijven',
    explanation: 'Bij het berekenen van hoeken zet je de berekening erbij én de gebruikte regel tussen haakjes achter het antwoord.',
  },
];
